trigger:
  batch: "true"
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - azure-pipelines.yml
    
pool: myagent1
pr: none
jobs:
- job: Deploy
  variables:
  - group: sfdx-org-dev
  steps:
  #- task: NodeTool@0
   # inputs:
    # versionSpec: '16.x'
    #displayName: 'Install Node.js'
   - task: UsePythonVersion@0
     inputs:
      versionSpec: 3.7.9
      addToPath: true
      disableDownloadFromRegistry: false
   - script: |
      # Install Salesforce CLI
      npm install -g sfdx-cli
     displayName: 'Install Salesforce CLI'

   - script: |
      # Verify Salesforce CLI installation
      sfdx --version
     displayName: 'Verify Salesforce CLI Installation'
  
   
   - task: DownloadSecureFile@1
     name: jwtKey
     displayName: 'Download Server JWT Key'
     inputs:
        secureFile: 'server.key'
   - bash: 
        sfdx force:auth:jwt:grant --clientid $(Clientid) --jwtkeyfile ./buildfiles/server.key --username $(SalesforceUserName) --instanceurl $(InstanceUrl) -a $(OrgAlias)
     displayName: Authorize salesforce org
  
 
   - bash: 
        sfdx force:source:deploy -x ./manifest/package.xml -u $(OrgAlias) -w 10
     displayName: Deploy source code to Salesforce Org
