trigger:
  batch: "true"
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - azure-pipelines.yml
    - pr/pr-build-dev.yml
    - pr/pr-build-qa.yml
    - pr/pr-build-uat.yml
    - pr/pr-build-master.yml
pool: myagent1
pr: none

jobs:
- job: Deploy
  variables:
  - group: sfdx-org-dev
  steps:

  - task: NodeTool@0
    inputs:
     versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install @salesforce/cli sfdx-cli --global
      sfdx --version
    displayName: 'Install Salesforce DX'
  #- task: UseNode@1
    #displayName: 'Use Node.js 16.15.0'
    #inputs:
     #   version: '16.15.0'
  
  - bash: 
        npm install sfdx-cli --global
    displayName: Install Salesforce CLI 
  - task: DownloadSecureFile@1
    name: jwtKey
    displayName: 'Download Server JWT Key'
    inputs:
        secureFile: 'server.key'
  - bash: 
        sfdx force:auth:jwt:grant --clientid $(Clientid) --jwtkeyfile ./buildfiles/server.key --username $(SalesforceUserName) --instanceurl $(InstanceUrl) -a $(OrgAlias)
    displayName: Authorize salesforce org
  
 
  - bash: 
        sfdx force:source:deploy -x ./manifest/package.xml -u $(OrgAlias) -w 10
    displayName: Deploy source code to Salesforce Org
